from .beneficio import Beneficio
from .beneficio_plato import BeneficioPlato
from .friends import Friends
from .menu import Menu
from .menu_tags import MenuTags
from .modelUser import ModelUser
from .reserva import Reserva
from .restaurant import Restaurant
from .review import Review
from .tag import Tag
from .user import User
from .user_favorites import UserFavorites
from .user_tags import UserTags
